$(document).ready(function(){appendUtmParamKundaliOp.initiate();var x=getCookie("Username");if(x!=""){$('#divAppBanner').hide();}
else
{setTimeout(function(){$('#divAppBanner').slideDown(2000);},10000);}});function fncCloseAppDownloadBanner()
{$("#divAppBanner").hide();var _bannercookie=getCookie("Username");if(_bannercookie=="")
{var user="close";setCookie("Username",user,30)}}
function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+"; "+expires;}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return "";}
$(function(){var dt=new Date();var year=dt.getFullYear()+10;var range='1920:'+year;$("#Kund_Dateofbirth").datepicker({changeMonth:true,yearRange:range,changeYear:true,dateFormat:'dd/mm/yy'});});$("#Kund_BirthTime").datetimepicker({format:"LTS"}).on("dp.change",function(e){}),document.querySelector("#kundliRegistrationFrm").addEventListener("submit",function(e){if($("#Kund_MobileError").hide(),$("#errorKundalimsg").hide(),$(this).valid()){e.preventDefault();var t=$("#kundliRegistrationFrm"),n=$('input[name="__RequestVerificationToken"]',t).val(),i={Kund_Name:$("#Kund_Name").val(),Kund_Dateofbirth:$("#Kund_Dateofbirth").val(),Kund_EmailAddress:$("#Kund_EmailAddress").val(),Kund_BirthTime:$("#Kund_BirthTime").val(),Kund_BirthPlace:$("#Kund_BirthPlace").val(),Kund_PhoneNumber:$("#Kund_PhoneNumber").val(),Kund_PhoneCode:$("#Kund_PhoneCode").val(),Kund_UtmCampaign:$("#Kund_UtmCampaign").val(),Kund_UtmSource:$("#Kund_UtmSource").val(),Kund_UtmContent:$("#Kund_UtmContent").val(),Kund_UtmMedium:$("#Kund_UtmMedium").val(),Kund_UtmTerm:$("#Kund_UtmTerm").val(),Kund_Latitude:$("#Kund_Latitude").val(),Kund_Longitude:$("#Kund_Longitude").val(),Kund_Timezone:$("#Kund_Timezone").val(),__RequestVerificationToken:n,SignUpType:"KundliRegistration"};if(CountryId=i.Kund_PhoneCode.match(/\(([^)]+)\)/)[1],""!=CountryId){var d=new RegExp("^[0-9]{10}$"),u=new RegExp("^[0-9]");if("IN"===CountryId||"US"===CountryId||"CA"===CountryId){if(null==i.Kund_PhoneNumber||!d.test(i.Kund_PhoneNumber))return $("#Kund_MobileError").show(),$("#Kund_PhoneNumber-error").hide(),$("#Kund_MobileError").html("Enter 10 digit mobile number"),!1;$("#Kund_MobileError").hide()}else{if(!(i.Kund_PhoneNumber.length>3&&i.Kund_PhoneNumber.length<17&&u.test(i.Kund_PhoneNumber)))return $("#Kund_MobileError").show(),$("#Kund_PhoneNumber-error").hide(),$("#Kund_MobileError").html("Enter your valid mobile number"),!1;$("#Kund_MobileError").hide()}}
var a=$("#kundliRegistrationFrm").find("[type='submit']").text();if($("#kundliRegistrationFrm").find("[type='submit']").text("Please wait.."),$("#kundliRegistrationFrm").find("[type='submit']").attr("disabled",!0),"True"==Isuser)return void
$.ajax({type:"POST",url:"/contentsyn/kundli/kundliresults",data:i,success:function(e){e.success?($("#kundliRegistrationFrm").find("[type='submit']").text("Redirecting.."),window.location=e.redirectUrl+"?Kund_Name="+e.data.kund_Name+"&Kund_Dateofbirth="+e.data.kund_Dateofbirth+"&Kund_BirthTime="+e.data.kund_BirthTime+"&Kund_Longitude="+e.data.kund_Longitude+"&Kund_Latitude="+e.data.kund_Latitude+"&Kund_Timezone="+e.data.kund_Timezone):($("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a),$("#errorKundalimsg").show().text(e.message))},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}});$.ajax({type:"POST",url:"/contentsyn/kundli/kundlitilepagenew",data:i,success:function(e){e.success?($("#kundliRegistrationFrm").find("[type='submit']").text("Redirecting.."),window.location=e.redirectUrl+"?Kund_Name="+e.data.kund_Name+"&Kund_Dateofbirth="+e.data.kund_Dateofbirth+"&Kund_BirthTime="+e.data.kund_BirthTime+"&Kund_Longitude="+e.data.kund_Longitude+"&Kund_Latitude="+e.data.kund_Latitude+"&Kund_Timezone="+e.data.kund_Timezone):($("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a),$("#errorKundalimsg").show().text(e.message))},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});var appendUtmParamKundaliOp={initiate:function(){$.when(astroyogiUtmParamOps.utmParamSetStat).then(function(){var e=astroyogiUtmParamOps.getUtmParam();null!=e&&($("#Kund_UtmSource").val(e.utmSource),$("#Kund_UtmCampaign").val(e.utmCampaign),$("#Kund_UtmContent").val(e.utmContent),$("#Kund_UtmMedium").val(e.utmMedium),$("#Kund_UtmTerm").val(e.utmTerm))})}};var array=null;$('#Kund_BirthPlace').keyup(function(){if($("#Kund_BirthPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#Kund_BirthPlace").val()},success:function(result){if(result.success==true){array=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#Kund_BirthPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];if(details.latitute==null||details.latitute==''||details.latitute=='undefined')
{details.latitute="19.076";details.longitutde="72.8777";details.timeZone="5.2";}
$("#Kund_Latitude").val(details.latitute);$("#Kund_Longitude").val(details.longitutde);$("#Kund_Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_Timezone").val(t)}}},a.send()}
var selectecItem=jsonString.filter(function(value){$("#Kund_BirthPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initialize();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});function initialize(){var e=new google.maps.places.Autocomplete(document.getElementById("Kund_BirthPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$("#Kund_Latitude").val(""),$("#Kund_Longitude").val(""),$("#Kund_Timezone").val("");var t=e.getPlace(),n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Kund_Latitude").val(n),$("#Kund_Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_Timezone").val(t)}}},a.send()})}
$(document).ready(function(){});