function showLocation(position){var latitude=position.coords.latitude;var longitude=position.coords.longitude;var latlongvalue=position.coords.latitude+","
+position.coords.longitude;var timestamp=position.coords.timestamp;if(latitude!=null&&longitude!=null&&timestamp!=null)
{$('#Latitude').val(latitude);$('#Longitude').val(longitude);$('#Timezone').val(timestamp);GetTithi();}
console.log(latitude,longitude);}
function errorHandler(err){if(err.code==1){alert("Error: Access is denied!");}else if(err.code==2){alert("Error: Position is unavailable!");}}
$(function(){$("#TodayPanchangDate").datepicker({changeMonth:true,changeYear:true,dateFormat:'dd MM yy'});});function showDate(date){alert('The date chosen is '+date);}
var array=null;$('#PanchangPlace').keyup(function(){if($("#PanchangPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#PanchangPlace").val()},success:function(result){if(result.success==true){array=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#PanchangPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];$("#Latitude").val(details.latitute);$("#Longitude").val(details.longitutde);$("#Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Timezone").val(t)}}},a.send();}
$("#dailyLocation").hide();var selectecItem=jsonString.filter(function(value){$("#PanchangPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initialize();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});function initialize(){var e=new google.maps.places.Autocomplete(document.getElementById("PanchangPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$("#Latitude").val(""),$("#Longitude").val(""),$("#Timezone").val("");n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Latitude").val(n),$("#Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Timezone").val(t)}}},a.send()})}
function GetPanchang()
{var data={};if($("#PanchangPlace").val()=="undefined"||$("#PanchangPlace").val()=="")
{$("#dailyLocation").text("Please Select Location");return false;}
if($('#Latitude').val()==""&&$('#Longitude').val()==""&&$('#Timezone').val()=="")
{$("#dailyLocation").text("");$("#dailyLocation").text("Invalid location");return false;}
var cityname=$("#PanchangPlace").val();var date2=$('#TodayPanchangDate').val();if(date2==""){var date=new Date();data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();}else{var date=new Date(date2);console.log(date);data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();}
var dt=new Date();data.Hour=dt.getHours();data.Min=dt.getMinutes();data.Lat=$('#Latitude').val();data.Lon=$('#Longitude').val();data.Tzone=$('#Timezone').val();InputData=data;$.ajax({type:'get',url:'/ContentSyn/kundli/GetTithiDetails',dataType:'json',data:{objStr:JSON.stringify(data)},success:function(response){if(response.data){var _panchangdata=response.data;$("#tithipan").text(_panchangdata.tithi.details.tithi_name);$("#pakshapan").text(_panchangdata.paksha);$("#sunsignpan").text(_panchangdata.sun_sign);$("#moonsignpan").text(_panchangdata.moon_sign);$("#sunrisepan").text(_panchangdata.sunrise);$("#sunsetpan").text(_panchangdata.sunset);$("#moonrisepan").text(_panchangdata.moonrise);$("#moonsetpan").text(_panchangdata.moonset);$("#muhuratpan").text(_panchangdata.abhijit_muhurta.start+" to "+_panchangdata.abhijit_muhurta.end);$("#rahukalpan").text(_panchangdata.rahukaal.start+" to "+_panchangdata.rahukaal.end);$("#yamagandapan").text(_panchangdata.yamghant_kaal.start+" to "+_panchangdata.yamghant_kaal.end);$("#gulikapan").text(_panchangdata.guliKaal.start+" to "+_panchangdata.guliKaal.end);$("#vaarpan").text(_panchangdata.day);$("#nakshatrapan").text(_panchangdata.nakshatra.details.nak_name);$("#karanpan").text(_panchangdata.karan.details.karan_name);$("#vikrampan").text(_panchangdata.vikram_samvat);$("#kalipan").text(_panchangdata.yamghant_kaal.start+" to "+_panchangdata.yamghant_kaal.end);$("#pakshapan").text(_panchangdata.paksha);$("#amantapan").text(_panchangdata.hindu_maah.amanta);$("#purnimantapan").text(_panchangdata.hindu_maah.purnimanta);$("#yogpan").text(_panchangdata.yog.details.yog_name+" till "+_panchangdata.yog.end_time.hour+":"+_panchangdata.yog.end_time.minute+":"+_panchangdata.yog.end_time.second);$("#ritupan").text(_panchangdata.ritu);$("#shakasamvatpan").text(_panchangdata.shaka_samvat);$("#yamghantpan").text(_panchangdata.yamghant_kaal.start+" to "+_panchangdata.yamghant_kaal.end);$("#gulikapan").text(_panchangdata.guliKaal.start+" to "+_panchangdata.guliKaal.end);$("#cityName").text(cityname);if(date2!=""){var dateVar=date2;var dsplit=dateVar.split("/");var d=new Date(dsplit[0],dsplit[1]-1,dsplit[2]);$("#panchangtoday").text(dateVar);}else{$("#panchangtoday").text(date.toDateString());}}}});}
$(document).ready(function(){$("#TodayPanchangDate").datepicker({dateFormat:"dd MM yy"}).datepicker("setDate",new Date());});