$(function(){var dt=new Date();var year=dt.getFullYear()+10;var range='1920:'+year;$("#Kund_F_Dateofbirth").datepicker({changeMonth:true,yearRange:range,changeYear:true,dateFormat:'dd MM yy'});$("#Kund_M_Dateofbirth").datepicker({changeMonth:true,yearRange:range,changeYear:true,dateFormat:'dd MM yy'});$('#Kund_F_BirthTime').datetimepicker({format:'LT'});$('#Kund_M_BirthTime').datetimepicker({format:'LT'});});var array=null;$('#Kund_M_BirthPlace').keyup(function(){if($("#Kund_M_BirthPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#Kund_M_BirthPlace").val()},success:function(result){if(result.success==true){array=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#Kund_M_BirthPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];$("#Kund_M_Latitude").val(details.latitute);$("#Kund_M_Longitude").val(details.longitutde);$("#Kund_M_Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_M_Timezone").val(t)}}},a.send()}
var selectecItem=jsonString.filter(function(value){$("#Kund_M_BirthPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initializeM();initializeF();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});var array2=null;$('#Kund_F_BirthPlace').keyup(function(){if($("#Kund_F_BirthPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#Kund_F_BirthPlace").val()},success:function(result){if(result.success==true){array2=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#Kund_F_BirthPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array2.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];$("#Kund_F_Latitude").val(details.latitute);$("#Kund_F_Longitude").val(details.longitutde);$("#Kund_F_Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_F_Timezone").val(t)}}},a.send()}
var selectecItem=jsonString.filter(function(value){$("#Kund_F_BirthPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initializeM();initializeF();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});function initializeM(){var e=new google.maps.places.Autocomplete(document.getElementById("Kund_M_BirthPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$('#Kund_M_Timezone').val("");$("#Kund_M_Latitude").val(""),$("#Kund_M_Longitude").val(""),$("#Kund_M_Timezone").val("");var t=e.getPlace(),n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Kund_LatKund_M_Latitudeitude").val(n),$("#Kund_M_Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_M_Timezone").val(t)}}},a.send()})}
function initializeF(){var e=new google.maps.places.Autocomplete(document.getElementById("Kund_F_BirthPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$('#Kund_F_Timezone').val("");$("#Kund_F_Latitude").val(""),$("#Kund_F_Longitude").val(""),$("#Kund_F_Timezone").val("");var t=e.getPlace(),n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Kund_F_Latitude").val(n),$("#Kund_F_Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_F_Timezone").val(t)}}},a.send()})}