$(document).ready(function(){$("#Nakshatra").datepicker({dateFormat:"dd MM yy"}).datepicker("setDate",new Date());$.ajax({type:'get',url:'/ContentSyn/panchang/GetGeoLocation',success:function(response){if(response.data){_geoLocationdata=response.data;var _geoLocationdata1=JSON.stringify(_geoLocationdata);localStorage.setItem('geoLocationData',_geoLocationdata1);$.ajax({type:'get',url:'/ContentSyn/kundli/GetTithiDetails',dataType:'json',data:{objStr:JSON.stringify(_geoLocationdata)},success:function(result){if(result.data){_panchangdata=result.data;var _panchangdata1=JSON.stringify(_panchangdata);localStorage.setItem('panchangdata',_panchangdata1);var _panchangdata=JSON.parse(localStorage.getItem('panchangdata'));var _geoLocationdata=JSON.parse(localStorage.getItem('geoLocationData'));var today=new Date();var date=new Date();date.setDate(today.getDate()+1);var data={};data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();var dt=new Date();data.Hour=dt.getHours();data.Min=dt.getMinutes();data.Lat=_geoLocationdata.lat;data.Lon=_geoLocationdata.lon;data.Tzone=_geoLocationdata.tzone;InputData=data;$.ajax({type:'get',url:'/ContentSyn/kundli/GetTithiDetails',dataType:'json',data:{objStr:JSON.stringify(data)},success:function(result){if(result.data){$("#nakshatradata").text(_panchangdata.nakshatra.details.nak_name+" till "+_panchangdata.nakshatra.end_time.hour+":"+_panchangdata.nakshatra.end_time.minute+":"+_panchangdata.nakshatra.end_time.second+" After That "+result.data.nakshatra.details.nak_name);$("#cityName").text(_geoLocationdata.city);}}});}}});}}});});function showLocation(position){var latitude=position.coords.latitude;var longitude=position.coords.longitude;var latlongvalue=position.coords.latitude+","+
position.coords.longitude;var timestamp=position.coords.timestamp;if(latitude!=null&&longitude!=null&&timestamp!=null){$('#Latitude').val(latitude);$('#Longitude').val(longitude);$('#Timezone').val(timestamp);GetTithi();}
console.log(latitude,longitude);}
function errorHandler(err){if(err.code==1){alert("Error: Access is denied!");}else if(err.code==2){alert("Error: Position is unavailable!");}}
$(function(){$("#Nakshatra").datepicker({changeMonth:true,changeYear:true,dateFormat:'dd MM yy'});});var googlihitcheck=0;var array=null;$('#PanchangPlace').keyup(function(){if($("#PanchangPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#PanchangPlace").val()},success:function(result){if(result.success==true){array=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#PanchangPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];$("#Latitude").val(details.latitute);$("#Longitude").val(details.longitutde);$("#Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Timezone").val(t)}}},a.send();}
var selectecItem=jsonString.filter(function(value){$("#PanchangPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initialize();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});function initialize(){var e=new google.maps.places.Autocomplete(document.getElementById("PanchangPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$("#Latitude").val(""),$("#Longitude").val(""),$("#Timezone").val("");var t=e.getPlace(),n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Latitude").val(n),$("#Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Timezone").val(t)}}},a.send()})}
var todayNakshatra=null;function GetNakshatra(){var data={};if($("#PanchangPlace").val()==""){$("#nakshatraLocation").text("Please Select Location");return false;}
if($('#Latitude').val()==""&&$('#Longitude').val()==""&&$('#Timezone').val()=="")
{$("#nakshatraLocation").text("");$("#nakshatraLocation").text("Select Valid location");return false;}
var cityname=$("#PanchangPlace").val();var date2=$('#Nakshatra').val();if(date2==""){var date=new Date();data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();}else{var date=new Date(date2);console.log(date);data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();}
var dt=new Date();data.Hour=dt.getHours();data.Min=dt.getMinutes();data.Lat=$('#Latitude').val();data.Lon=$('#Longitude').val();data.Tzone=$('#Timezone').val();InputData=data;$.ajax({type:'get',url:'/ContentSyn/kundli/GetTithiDetails',dataType:'json',data:{objStr:JSON.stringify(data)},success:function(result){if(result.data){todayNakshatra=result.data;var data={};if($('#Nakshatra').val()=="")
{var today=new Date();var date=new Date();date.setDate(today.getDate()+1);data.Day=date.getDate();data.Month=date.getMonth()+1;data.Year=date.getFullYear();}
else
{var date=new Date(date2);data.Day=date.getDate()+1;data.Month=date.getMonth()+1;data.Year=date.getFullYear();}
var dt=new Date();data.Hour=dt.getHours();data.Min=dt.getMinutes();data.Lat=$('#Latitude').val();data.Lon=$('#Longitude').val();data.Tzone=$('#Timezone').val();InputData=data;$.ajax({type:'get',url:'/ContentSyn/kundli/GetTithiDetails',dataType:'json',data:{objStr:JSON.stringify(data)},success:function(result){if(result.data){$("#nakshatradata").text(todayNakshatra.nakshatra.details.nak_name+" till "+todayNakshatra.nakshatra.end_time.hour+":"+todayNakshatra.nakshatra.end_time.minute+":"+todayNakshatra.nakshatra.end_time.second+" After That "+result.data.nakshatra.details.nak_name);$("#cityName").text($("#PanchangPlace").val());if(date2!=""){var dateVar=date2;var dsplit=dateVar.split("/");var d=new Date(dsplit[0],dsplit[1]-1,dsplit[2]);$("#nakshatratoday").text(dateVar);}else{$("#nakshatratoday").text(date.toDateString());}}}});}}});}